### ISSUE TITLE
No binding for backspace

### ISSUE THREAD

**Issue by zikes** [PolymerElements/iron-a11y-keys-behavior#10] opened 2015-06-25 15:04 UTC
There is currently no way to bind to backspace.

**Comment by stevehansen** [comment] 2015-07-03 19:51
Took me some time to figure out that I couldn't use "insert" because it wasn't in the list.

I was using http://www.openjs.com/scripts/events/keyboard_shortcuts/ before and this one has a lot more keys predefined.

Or maybe make it possible to use any hex code?

**Comment by cdata** [comment] 2015-10-26 17:54
I'm going to close this as a duplicate of #12 .

**Closed by cdata** 2015-10-26 17:54 UTC
